### ISSUE TITLE
Add maven support

### ISSUE THREAD

**Issue by pavog** [Rexcantor/Triton#48]
### Problem info:

**Issue type:** Feature request
#### Description:
Please add support for maven so that projects using maven can add TritonAPI properly.
When developers want to use Triton in their mavne project they have the choice to not download the api.jar but:

1. Use [jitpack](https://jitpack.io/):

You just need to add the jitpack repo:

```
	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
```

And add the dependency:

```
	<dependency>
	    <groupId>com.github.Rexcantor</groupId>
	    <artifactId>Triton</artifactId>
	    <version>master-SNAPSHOT</version>
	</dependency>
```

2. Or if @Rexcantor has a repository (like sonatype nexus or jfrog artifactory) he may deploy the maven artifacts to it and we just need to add his repository and we can use the correct dependency groupId (com.rexcantor64.triton) and artifactId (api).

**Comment by Rexcantor** [comment]
Thanks for helping! I'll be looking into this today.

**Comment by pavog** [comment]
You just need to review pr #49 :)
