### ISSUE TITLE
HubConnector

### ISSUE THREAD

**Issue by alexlazarev98** [Rexcantor/Triton#53]
### Server info:

**MLP version:** 1.1.0
**Minecraft version:** 1.13
**Server software:** paper spigot
**Using BungeeCord:** Waterfall  

### Problem info:

**Issue type:** bug
#### Description:
/hub > An internal error occured. https://www.spigotmc.org/resources/hub-connector-multi-hub-ping-find-hub-command-bungee-reconnect.53438/

### Error logs (in case it's a bug report):
https://pastebin.com/thzjqQ8D

**Comment by Rexcantor** [comment]
Fix will be available in 1.1.1.
